Repository smaranjitghose/ParulUniversityMEAN, pull requests merged in 2024-01, with the labels that each got.

#15 6A13 Group 5
  Final_Projects.MD
Labels: 6A13

#14 6A13 group 2
  Final_Projects.MD
Labels: 6A13

#10 6A13 - Group 8
  Final_Projects.MD
Labels: 6A13

#12 Update Final_Projects.MD
  Final_Projects.MD
Labels: 6A16

#16 Update Capstone_Project_Allocation.MD
  Capstone_Project_Allocation.MD
Labels: 6A16

#18 6A14 Group-8
  Capstone_Project_Allocation.MD
  README.MD
Labels: 6A14

#17 6A16 - Group 8
  Capstone_Project_Allocation.MD
Labels: 6A16

#22 6A13 - Group 14
  Capstone_Project_Allocation.MD
Labels: 6A13

#21 6A14 - Group 11
  Capstone_Project_Allocation.MD
Labels: 6A14
